# Generated by Django 3.2.12 on 2022-03-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_ocr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Post',
        ),
    ]
