# Generated by Django 3.2.12 on 2022-04-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_ocr', '0002_rename_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trainingpdf',
            field=models.FileField(blank=True, null=True, upload_to='trainingpdf/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='processed_image',
            field=models.FileField(blank=True, null=True, upload_to='processing_images/'),
        ),
    ]
